all: ccadd cclist ccitem ccdel  ccmatch ccyear ccedit ccmain

ccadd: ccadd.c cc.h
	gcc ccadd.c  -o ccadd -g

cclist: cclist.c cc.h
	gcc cclist.c -o cclist -g

ccitem: ccitem.c cc.h
	gcc ccitem.c -o ccitem -g

ccdel: ccdel.c cc.h
	gcc ccdel.c -o ccdel -g

ccmatch: ccmatch.c cc.h
	gcc ccmatch.c -o ccmatch -g

ccyear: ccyear.c cc.h
	gcc ccyear.c -o ccyear -g

ccedit: ccedit.c cc.h
	gcc ccedit.c -o ccedit -g

ccmain: ccmain.c cc.h
	gcc ccmain.c -o ccmain -g



